### ISSUE TITLE
Cannot locate the bulk2space.py script and directory after installation

### ISSUE THREAD

**Issue by loganminhdang** [ZJUFanLab/bulk2space#4]
Hi, I'm writing to seek your assistance on an issue I'm having. After installation of the conda environment, I cannot locate the bulk2space directory, which should contain the bulk2space python script to run the algorithm. The installation also seems incomplete, seeing that after I manually retrieve the python script from your Github page, I received the following error message: 
Traceback (most recent call last):
  File "bulk2space.py", line 2, in <module>
    from utils.tool import *
ModuleNotFoundError: No module named 'utils'

I would appreciate any guidance. Thanks!

**Comment by ForwardYang98** [comment]
Hi, you need to download the bulk2space package from Github and unzip it, then run the command `cd xx/bulk2space-main` and `pip install -r requirements.txt` in the command line to install the required packages in the conda environment (xx is your file path). After all packages are installed, you can then run the command `cd bulk2space` to enter the bulk2space folder and make the analysis.
Hope it will help you.

**Comment by loganminhdang** [comment]
Thank you for the guidance, it was clear. However, upon trying to execute the command, I received the following error: 

Traceback (most recent call last):
  File "bulk2space.py", line 243, in <module>
    main()
  File "bulk2space.py", line 50, in main
    sc = scanpy.AnnData(input_sc_data.T)
  File "/well/jagannath/users/xjp886/Quang/conda/skylake/envs/bulk2space/lib/python3.8/site-packages/anndata/_core/anndata.py", line 291, in __init__
    self._init_as_actual(
  File "/well/jagannath/users/xjp886/Quang/conda/skylake/envs/bulk2space/lib/python3.8/site-packages/anndata/_core/anndata.py", line 435, in _init_as_actual
    X = ensure_df_homogeneous(X, "X")
  File "/well/jagannath/users/xjp886/Quang/conda/skylake/envs/bulk2space/lib/python3.8/site-packages/anndata/utils.py", line 139, in ensure_df_homogeneous
    arr = df.sparse.to_coo().tocsr()
  File "/well/jagannath/users/xjp886/Quang/conda/skylake/envs/bulk2space/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 332, in to_coo
    dtype = find_common_type(self._parent.dtypes)
  File "/well/jagannath/users/xjp886/Quang/conda/skylake/envs/bulk2space/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1464, in find_common_type
    raise ValueError("no types given")
ValueError: no types given

Do you have an idea of what this error may mean?

**Comment by ForwardYang98** [comment]
Hi, I haven't received this error before, but it seems this is caused by the `scanpy.AnnData` function. You could send the code and a demo data to my e-mail: qianjingyang@zju.edu.cn and I will check again.

**Comment by loganminhdang** [comment]
Hey, thanks for your reply. I resolved the error (it had something to do with the gene names for the input). I'm trying to use Bulk2Space to deconvolute using a hypothalamic bulk dataset I created. I received the following error: 

Traceback (most recent call last):
  File "bulk2space.py", line 243, in <module>
    main()
  File "bulk2space.py", line 94, in main
    bulk_rep = bulk_marker.reshape(bulk_marker.shape[0], )
ValueError: cannot reshape array of size 39768 into shape (3314,)

It probably has something to do with my input bulk expression matrix, which does not correspond well with the rest of input files which you generated. Any guidance will be appreciated. Thank you for your time

**Comment by ForwardYang98** [comment]
Hi, this is due to the formatting error in the bulk expression matrix of your input. You can check the data again by following the instructions on Github. The format of input bulk expression data is supposed to be `.csv` with only one column of sample and the index of genes.
